---
title: "CodePortfolio"
author: "I-Ting Cheng"
date: "June 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Dplyr Package###
# Install the dplyr package
install.packages(dplyr)

# Load the deplyr package
library(dplyr)

The Dplyr package provides different grammers to manipulate the data and operate on the data frame, some comman grammers are as followed:
  #Select
  #Filter
  #Arrange
  #Rename
  #Mutate
  #Summarize
  #%>%
  
#Use dplyr package to analyze dataset: Chicago
  
#Read in the data
chicago <- readRDS("C:/Users/user/Harrisburg U/Exploratory Data Analysis/Weeklycode/chicago.rds")
# Look at the dataset - basic characteristics:
dim(chicago) - Number of observations & variables
str(chicago) - Number of observations & variables + Variables type
head(chicago)- First few rows 
nrow(chicago)
ncolumn(chicago)
names(chicago)[1:3]

##select Function
subset <- select(chicago, city:dptp)
head(subset)

##filter Function
chic.f <- filter(chicago, pm25tmean2 > 30)
str(chic.f)
summary(chic.f$pm25tmean2)
chic.f <- filter(chicago, pm25tmean2 > 30 & tmpd > 80)
select(chic.f, date, tmpd, pm25tmean2)

##arrange Function
chicago <- arrange(chicago, date)
head(select(chicago, date, pm25tmean2), 3)
tail(select(chicago, date, pm25tmean2), 3)
chicago <- arrange(chicago, desc(date))
head(select(chicago, date, pm25tmean2), 3)
tail(select(chicago, date, pm25tmean2), 3)

##rename Function
head(chicago[, 1:5], 3)
chicago <- rename(chicago, dewpoint = dptp, pm25 = pm25tmean2)
head(chicago[, 1:5], 3)

##mutate Function
chicago <- mutate(chicago, pm25detrend = pm25 - mean(pm25, na.rm = TRUE))
head(chicago)
head(transmute(chicago, 
               +pm10detrend = pm10tmean2 - mean(pm10tmean2, na.rm = TRUE),
               +o3detrend = o3tmean2 - mean(o3tmean2, na.rm = TRUE)))
##group_by Function
chicago <- mutate(chicago, year = as.POSIXlt(date)$year + 1900)
years <- group_by(chicago, year)
summarize(years, pm25 = mean(pm25, na.rm = TRUE), 
          +o3 = max(o3tmean2, na.rm = TRUE), 
          +no2 = median(no2tmean2, na.rm = TRUE))
qq <- quantile(chicago$pm25, seq(0, 1, 0.2), na.rm = TRUE)
chicago <- mutate(chicago, pm25.quint = cut(pm25, qq))
quint <- group_by(chicago, pm25.quint)
summarize(quint, o3 = mean(o3tmean2, na.rm = TRUE), 
          +no2 = mean(no2tmean2, na.rm = TRUE))
##%>% Function
third(second(first(x)))
first(x) %>% second %>% third
mutate(chicago, pm25.quint = cut(pm25, qq)) %>%    
  +group_by(pm25.quint) %>% 
  +summarize(o3 = mean(o3tmean2, na.rm = TRUE), 
  +no2 = mean(no2tmean2, na.rm = TRUE))

mutate(chicago, month = as.POSIXlt(date)$mon + 1) %>% 
  +group_by(month) %>% 
  + summarize(pm25 = mean(pm25, na.rm = TRUE), 
  +o3 = max(o3tmean2, na.rm = TRUE), 
  +no2 = median(no2tmean2, na.rm = TRUE))


---

###Exploratory data anaylsis### 

#Use exploratory anaylsis to analyze dataset: avgpm25

class <- c("numeric", "character", "factor", "numeric", "numeric")
pollution <- read.csv("data/avgpm25.csv", colClasses = class)
head(pollution)
str(pollution)
fivenum(pollution$pm25)
summary(pollution$pm25)

#Boxplot
boxplot(pollution$pm25, col = "blue")
filter(pollution, pm25 > 15)
library(maps)
map("county", "california")
with(filter(pollution, pm25 > 15), points(longitude, latitude))
##Multiple Boxplot
boxplot(pm25 ~ region, data = pollution, col = "red")
##Overlaying feature
boxplot(pollution$pm25, col = "blue")
abline(h = 12)

#Histogram
hist(pollution$pm25, col = "green")
hist(pollution$pm25, col = "green")
rug(pollution$pm25)
hist(pollution$pm25, col = "green", breaks = 100)
rug(pollution$pm25)
##Overlaying feature
hist(pollution$pm25, col = "green")
abline(v = 12, lwd = 2)
abline(v = median(pollution$pm25), col = "magenta", lwd = 4)
## Multiple Histogram
par(mfrow = c(2, 1), mar = c(4, 4, 2, 1))
hist(subset(pollution, region == "east")$pm25, col = "green")
hist(subset(pollution, region == "west")$pm25, col = "green")

#Barplot
library(dplyr)
table(pollution$region) %>% barplot(col = "wheat")

#Scatterplot
with(pollution, plot(latitude, pm25))
abline(h = 12, lwd = 2, lty = 2)
##Scatterplot with color
with(pollution, plot(latitude, pm25, col = region))
abline(h = 12, lwd = 2, lty = 2)
levels(pollution$region)
##Multiple Scatterplot
par(mfrow = c(1, 2), mar = c(5, 4, 2, 1))
with(subset(pollution, region == "west"), plot(latitude, pm25, main = "West"))
with(subset(pollution, region == "east"), plot(latitude, pm25, main = "East"))

---
###Base plotting system###
The base plotting system includes fuctions as belowed:
  #pch: plotting symbol
  #lty: the line type 
  #lwd: line width
  #col: plotting color
  #xlab
  #ylab
  #las: orientation of axis 
  #bg: background color
  #mar: margin size
  #oma: outer margin size 
  #mfrow: number of plots/row
  #mfcol: number of plots/row
The base plotting system aesthetic 
  #lines: add lines
  #points: add points
  #text: add text label
  #title: add annotations
  #mtext: add arbitrary text to the margin
  #axis: add axis label
  
#Use base plotting system to analyze dataset: cars

data(cars) 
with(cars, plot(speed, dist))
title("Speed vs. Stopping distance")
state <- data.frame(state.x77, region = state.region)
xyplot(Life.Exp ~ Income | region, data = state, layout = c(4, 1))
  
#Use base plotting system to analyze dataset: airquality

library(datasets)
hist(airquality$Ozone)  
airquality <- transform(airquality, Month = factor(Month))
boxplot(Ozone ~ Month, airquality, xlab = "Month", ylab = "Ozone (ppb)")
with(airquality, plot(Wind, Ozone))

---
###Aesthetic Setting###
#Set colors
set.seed(19)
x <- rnorm(30)
y <- rnorm(30)
plot(x, y, col = rep(1:3, each = 10), pch = 19)
legend("bottomright", legend = paste("Group", 1:3), col = 1:3, pch = 19, bty = "n")

#Set colors
par(mfrow = c(1, 2))
image(volcano, col = heat.colors(10), main = "heat.colors()")
image(volcano, col = topo.colors(10), main = "topo.colors()")

#colorRamp()
pal <- colorRamp(c("red", "blue"))
pal(0)
pal(1)
pal(0.5)

#colorRampPalette()
pal <- colorRampPalette(c("red", "yellow"))
pal(2)
pal(10)

#RColorBrewer Package
library(RColorBrewer)
display.brewer.all()
cols <- brewer.pal(3, "BuGn")
cols
pal <- colorRampPalette(cols)
image(volcano, col = pal(20))

##SmoothScatter() function
set.seed(1)
x <- rnorm(10000)
y <- rnorm(10000)
smoothScatter(x, y)

#Set Transparency
rgb(1, 0, 0, 0.1)
set.seed(2)
x <- rnorm(2000)
y <- rnorm(2000)
plot(x, y, pch = 19)
plot(x, y, pch = 19, col = rgb(0, 0, 0, 0.15))

--
###Hierarchical Clustering###
Manhattan distance:
Distance=|A1???B1|+|A2???B2|+???+|An???Bn|

set.seed(1234)
x <- rnorm(12, rep(1:3, each = 4), 0.2)
y <- rnorm(12, rep(c(1, 2, 1), each = 4), 0.2)
plot(x, y, col = "blue", pch = 19, cex = 2)
text(x + 0.05, y + 0.05, labels = as.character(1:12))
dataFrame <- data.frame(x=x, y=y)
dist(dataFrame)
rdistxy <- as.matrix(dist(dataFrame))
diag(rdistxy) <- diag(rdistxy) + 100000
ind <- which(rdistxy == min(rdistxy), arr.ind = TRUE)
ind

plot(x, y, col = "blue", pch = 19, cex = 2)
text(x + 0.05, y + 0.05, labels = as.character(1:12))
points(x[ind[1, ]], y[ind[1, ]], col = "orange", pch = 19, cex = 2)

par(mfrow = c(1, 2))
plot(x, y, col = "blue", pch = 19, cex = 2, main = "Data")
text(x + 0.05, y + 0.05, labels = as.character(1:12))
points(x[ind[1, ]], y[ind[1, ]], col = "orange", pch = 19, cex = 2)

library(dplyr)
hcluster <- dist(dataFrame) %>% hclust
dendro <- as.dendrogram(hcluster)
cutDendro <- cut(dendro, h = (hcluster$height[1] + 0.00001))
plot(cutDendro$lower[[11]], yaxt = "n", main = "Begin building tree")

nextmin <- rdistxy[order(rdistxy)][3]
ind <- which(rdistxy == nextmin,arr.ind=TRUE)
ind

hClustering <- data.frame(x=x,y=y) %>% dist %>% hclust
plot(hClustering)

---
###K-means Cluttering###

set.seed(1234)
x <- rnorm(12, mean = rep(1:3, each = 4), sd = 0.2)
y <- rnorm(12, mean = rep(c(1, 2, 1), each = 4), sd = 0.2)
plot(x, y, col = "blue", pch = 19, cex = 2)
text(x + 0.05, y + 0.05, labels = as.character(1:12))

dataFrame <- data.frame(x, y)
kmeansObj <- kmeans(dataFrame, centers = 3)
names(kmeansObj)
kmeansObj$cluster

#Heatmap K-means
set.seed(1234)
dataMatrix <- as.matrix(dataFrame)[sample(1:12), ]
kmeansObj <- kmeans(dataMatrix, centers = 3)

par(mfrow = c(1, 2))
image(t(dataMatrix)[, nrow(dataMatrix):1], yaxt = "n", main = "Original Data")
image(t(dataMatrix)[, order(kmeansObj$cluster)], yaxt = "n", main = "Clustered Data")


Other practices:
----------------------------------------------------------------------------------------
##Latice package
install.packages("lattice")
library(lattice)
xyplot(pm25 ~ latitude | region, data = pollution)

---
##ggplot2 package
install.packages("ggplot2")
library(ggplot2)
qplot(latitude, pm25, data = pollution, facets = . ~ region)
data(mpg)
qplot(displ, hwy, data = mpg)


library(ggplot2)
with(airquality, { 
        plot(Temp, Ozone)
        lines(loess.smooth(Temp, Ozone))
})

ggplot(airquality, aes(Temp, Ozone)) + 
        geom_point() + 
        geom_smooth(method = "loess", se = FALSE)

library(ggplot2)
str(mpg)
qplot(displ, hwy, data = mpg)

#Aesthetic
qplot(displ, hwy, data = mpg, color = drv)

#Geom
qplot(displ, hwy, data = mpg, geom = c("point", "smooth"))

#Histogram
qplot(hwy, data = mpg, fill = drv, binwidth = 2)

#Boxplot
qplot(drv, hwy, data = mpg, geom = "boxplot")

#Facet
qplot(hwy, data = mpg, facets = drv ~ ., binwidth = 2)
qplot(displ, hwy, data = mpg, facets = . ~ drv)
qplot(displ, hwy, data = mpg, facets = . ~ drv) + geom_smooth()

----
#Gamminder package
# Load the gapminder package
install.packages(gapminder)

# Look at the gapminder dataset
print(gapminder)

library(gapminder)

# Sort in ascending order of lifeExp
gapminder %>%
  arrange(lifeExp)

# Sort in descending order of lifeExp
gapminder %>%
  arrange(desc(lifeExp))


---
##Tidyverse package

library(nycflights13)
library(tidyverse)
print(flights)

library(dplyr)
library(tibble)

df <-  filter(flights, month == 12, day == 30)

mean(df$dep_delay, na.rm = T)
mean(income$M_weekly, na.rm = T)
median(income$M_weekly, na.rm = T)
mean(income$M_weekly, trim=0.1, na.rm = T) 

install.packages("matrixStats")
library(matrixStats)
weightedMedian(income[["M_weekly"]], w=income[["M_weekly"]], na.rm=TRUE)
edit(weightedMedian)

sd(income$F_workers)
IQR(income$F_workers)
mad(income$F_workers)

income <- as.tibble(income)
income %>% filter(income$M_weekly > 2000) 
income$diff <- income$M_weekly-income$F_weekly
round(sd(income$diff, na.rm = TRUE), 2)
round(sd, 2)
income %>% glimpse()

data("mtcars")
sd(mtcars$mpg)
IQR(mtcars$mpg)
mad(mtcars$mpg)

str(US.EPA.data.2017)
filter(US.EPA.data.2017, is.na(US.EPA.data.2017$X2nd.Max.Value))
str(mpg)
data("faithful")
summary(faithful)

data("iris")
filter(iris$Petal.Length > 4.5

data("WHO")
summary(US.EPA.data.2017)
sum(is.na(US.EPA.data.2017$X2nd.Max.Value)) 
weightedMedian(mtcars$mpg)
median(mtcars$mpg)
scatterplot(mtcars$disp,mtcars$hp, size = 3, shape=17, colour = 'black', fill = 'red')

library("matrixStats")

# Load the gapminder package
library(gapminder)

# Load the dplyr package
library(dplyr)

# Look at the gapminder dataset
print(gapminder)

library(gapminder)
library(dplyr)

# Sort in ascending order of lifeExp
gapminder %>%
  arrange(lifeExp)

# Sort in descending order of lifeExp
gapminder %>%
  arrange(desc(lifeExp))
